server:
  port: 8080
#=================================================================================
# spring 组件相关设置
spring:
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 3000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vue?useUnicode=true&character=utf8
    username: root
    password: root
#=================================================================================
# mybatis plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: 'com.redis.entity'
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false